---
format: pdf
pdf-engine: lualatex
documentclass: ltjarticle
classoption: [a4paper]
cite-method: biblatex
biblatexoptions: [backend=biber, style=jpa, sorting=nyt]
bibliography: reference.bib
biblio-title: "引用文献"
---


# 欧文の文献


## 単著の本

@Broadbent1998 はこう述べている[@Broadbent1998]。


## 共著の本

- 著者がふたり

@Berger1972 はこう述べている[@Berger1972]。


- 著者が3人以上

@Isaac1980 はこう述べている[@Isaac1980]。


## 編書

- 編者がひとり

@Douglas1970 はこう述べている[@Douglas1970]。



- 編者が複数

@Rubington1965 はこう述べている[@Rubington1965]。




## 編書論文


@Mayer1995 はこう述べている[@Mayer1995]。



## 雑誌論文


@Abbott1995 はこう述べている[@Abbott1995]。


# 邦文の文献

## 単著の本

@oguma1995 はこう述べている[@oguma1995]。


## 共著の本

@miyajima1985 はこう述べている[@miyajima1985]。


## 編書

@kosaka1998 はこう述べている[@kosaka1998]。



## 編書論文

@Chuankyo1998 はこう述べている[@Chuankyo1998]。




## 雑誌論文

@sato1998 はこう述べている[@sato1998]。


## 学位論文

@ueno2013 はこう述べている[@ueno2013]。


## 翻訳書
@bourdieu1997HomoAkademikusu はこう述べている[@bourdieu1997HomoAkademikusu]。


## 報告書
### 科研費など（reportを使用）
@nasu2010ChiNoKozo はこう述べている[@nasu2010ChiNoKozo]。

### 政府刊行物など（miscを使用）
@dokuritsugyoseihojinnippongakujutsushinkokai2011JimbunGakuShakai ではこのように触れられている[@dokuritsugyoseihojinnippongakujutsushinkokai2011JimbunGakuShakai]。


## 学会発表
@watanabe2023NipponNoKenkyu はこう述べている[@watanabe2023NipponNoKenkyu]。


# 面倒なケース

## 同一年度で同じ著者の論文が複数ある場合

@Denning2022、@Denning2022a はこう述べている[@Denning2022; @Denning2022a]。

